blank_issues_enabled: false
contact_links:
    - name: ioBroker Community
      url: https://forum.iobroker.net/topic/82348/test-adapter-unifi-network
      about: Please ask and answer questions here.
